version: "3.8"
services:
  backend:
    build: "./web-app"
    ports: 
      - 8080:8080
    volumes:
      - ./web-app/src/:/web-app/src/
    env_file: .env
    networks:
      - db-network
    depends_on:
      - db
  db:
    build: "./db"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    networks:
      - db-network
    volumes:
      - data:/var/lib/mysql
      
networks:
  db-network:
    driver: bridge

volumes:
  data:
