version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ims_backend
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./src/:/src/
    networks:
      - ims-backend-network
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: ims_db
    environment:
      MYSQL_DATABASE: ims_project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - ims-backend-network
    volumes:
      - data:/var/lib/mysql

networks:
  ims-backend-network:
    driver: bridge

volumes:
  data: